package com.example.demo.model;

public enum ApplicantStatus {
    SCHEDULED,
    INVITING_FOR_INTERVIEW,
    NOT_QUALIFIED,
    NOT_ELIGIBLE_FOR_HIRE,
    NOT_INTERESTED,
    INTERVIEW_COMPLETED,
    INTERVIEW_NO_SHOW,
    HIRED,
    ORIENTATION_SCHEDULED,
    ORIENTATION_NO_SHOW,
    ORIENTATION_COMPLETED
}
